import { Asset } from 'expo-asset';
import { File } from 'expo-file-system';
import {
  PDFHexString,
  PDFName,
  PDFString,
  TextRenderingMode,
  beginText,
  endText,
  popGraphicsState,
  pushGraphicsState,
  setCharacterSqueeze,
  setFontAndSize,
  setTextMatrix,
  setTextRenderingMode,
  showText,
  type PDFDocument,
  type PDFPage,
  type PDFRef,
} from 'pdf-lib';
import type { OcrLine, PageOcr } from '../../types/models';

// --- Invisible OCR text for every script, via one "glyphless" font -------------------------------
//
// Same technique as Tesseract's PDF output. assets/fonts/glyphless.ttf (~600 bytes, generated by
// scripts/make-glyphless-font.py) has a single blank glyph. It's embedded as a Type0 font over a
// CIDFontType2 with Identity-H encoding, where:
//   - each character is written as its own Unicode code point used as the CID (2 bytes, BMP only);
//   - CIDToGIDMap sends every CID to that blank glyph, so no script needs real glyph outlines
//     (a CJK font would be 10+ MB);
//   - a ToUnicode CMap maps every CID back to the same code point, so search and copy recover the
//     original text, in logical order - Latin with accents, CJK, Devanagari, Bengali alike.
// Each OCR line is drawn with render mode 3 (invisible) and horizontally scaled (Tz) to span the
// line's box, so selection highlights sit on the ink.

const GLYPHLESS_FONT_MODULE = require('../../../assets/fonts/glyphless.ttf');

// Must match ADVANCE in scripts/make-glyphless-font.py (in 1/1000 em).
const GLYPH_ADVANCE = 500;
const FONT_RESOURCE_NAME = 'FOcrGlyphless';

let fontBytesPromise: Promise<Uint8Array> | null = null;

function loadGlyphlessFontBytes(): Promise<Uint8Array> {
  if (!fontBytesPromise) {
    fontBytesPromise = (async () => {
      const asset = Asset.fromModule(GLYPHLESS_FONT_MODULE);
      await asset.downloadAsync();
      if (!asset.localUri) throw new Error('textLayer: glyphless font asset has no localUri after downloadAsync()');
      return new File(asset.localUri).bytes();
    })();
    fontBytesPromise.catch(() => {
      fontBytesPromise = null;
    });
  }
  return fontBytesPromise;
}

function hex4(n: number): string {
  return n.toString(16).toUpperCase().padStart(4, '0');
}

// Identity ToUnicode CMap: CID n -> U+n across the BMP, as 256-code ranges (a bfrange may only vary
// in its last byte), skipping the surrogate block, in chunks of at most 100 per bfrange section.
function buildToUnicodeCMap(): string {
  const ranges: string[] = [];
  for (let hi = 0; hi < 256; hi++) {
    if (hi >= 0xd8 && hi <= 0xdf) continue;
    const start = hi << 8;
    ranges.push(`<${hex4(start)}> <${hex4(start + 0xff)}> <${hex4(start)}>`);
  }
  const sections: string[] = [];
  for (let i = 0; i < ranges.length; i += 100) {
    const chunk = ranges.slice(i, i + 100);
    sections.push(`${chunk.length} beginbfrange\n${chunk.join('\n')}\nendbfrange`);
  }
  return [
    '/CIDInit /ProcSet findresource begin',
    '12 dict begin',
    'begincmap',
    '/CIDSystemInfo << /Registry (Adobe) /Ordering (UCS) /Supplement 0 >> def',
    '/CMapName /Adobe-Identity-UCS def',
    '/CMapType 2 def',
    '1 begincodespacerange',
    '<0000> <FFFF>',
    'endcodespacerange',
    ...sections,
    'endcmap',
    'CMapName currentdict /CMap defineresource pop',
    'end',
    'end',
  ].join('\n');
}

// Every CID -> GID 1 (the blank glyph). 128 KB raw, a few hundred bytes once deflated.
function buildCidToGidMap(): Uint8Array {
  const map = new Uint8Array(0x10000 * 2);
  for (let i = 1; i < map.length; i += 2) map[i] = 1;
  return map;
}

// Embeds the glyphless font into `pdfDoc` once; pass the returned ref to drawOcrTextLayer.
export async function embedGlyphlessFont(pdfDoc: PDFDocument): Promise<PDFRef> {
  const context = pdfDoc.context;
  const fontBytes = await loadGlyphlessFontBytes();

  const fontFileRef = context.register(context.flateStream(fontBytes, { Length1: fontBytes.length }));
  const descriptorRef = context.register(
    context.obj({
      Type: 'FontDescriptor',
      FontName: 'GlyphLessFont',
      Flags: 5, // FixedPitch | Symbolic
      FontBBox: [0, 0, GLYPH_ADVANCE, 1000],
      ItalicAngle: 0,
      Ascent: 1000,
      Descent: 0,
      CapHeight: 1000,
      StemV: 80,
      FontFile2: fontFileRef,
    })
  );
  const cidToGidRef = context.register(context.flateStream(buildCidToGidMap()));
  const cidFontRef = context.register(
    context.obj({
      Type: 'Font',
      Subtype: 'CIDFontType2',
      BaseFont: 'GlyphLessFont',
      CIDSystemInfo: { Registry: PDFString.of('Adobe'), Ordering: PDFString.of('Identity'), Supplement: 0 },
      FontDescriptor: descriptorRef,
      DW: GLYPH_ADVANCE,
      CIDToGIDMap: cidToGidRef,
    })
  );
  const toUnicodeRef = context.register(context.flateStream(buildToUnicodeCMap()));
  return context.register(
    context.obj({
      Type: 'Font',
      Subtype: 'Type0',
      BaseFont: 'GlyphLessFont',
      Encoding: 'Identity-H',
      DescendantFonts: [cidFontRef],
      ToUnicode: toUnicodeRef,
    })
  );
}

// Where the page image was drawn, in PDF points (see pdfService's ImagePlacement).
export type TextLayerPlacement = { origin: { x: number; y: number }; heightPt: number; scale: number };

export type TextLayerStats = { linesDrawn: number; skippedChars: number };

// UTF-16 BMP code units as 4-hex-digit CIDs. Characters outside the BMP (emoji, rare CJK
// extensions) can't be a 2-byte CID and are dropped - and counted, never silently.
function encodeCids(text: string): { hex: string; count: number; skipped: number } {
  let hex = '';
  let count = 0;
  let skipped = 0;
  for (const ch of text) {
    const cp = ch.codePointAt(0) ?? 0;
    if (cp > 0xffff) {
      skipped++;
      continue;
    }
    hex += hex4(cp);
    count++;
  }
  return { hex, count, skipped };
}

function drawLine(page: PDFPage, fontName: PDFName, line: OcrLine, placement: TextLayerPlacement, stats: TextLayerStats) {
  const text = line.text.trim();
  if (!text) return;
  const { hex, count, skipped } = encodeCids(text);
  stats.skippedChars += skipped;
  if (count === 0) return;

  const { left, top, width, height } = line.bounding;
  const boxWidthPt = width * placement.scale;
  const boxHeightPt = height * placement.scale;
  if (!(boxWidthPt > 0) || !(boxHeightPt > 0)) return;

  // PDF's origin is bottom-left; OCR `top` is measured from the image's top edge, hence the flip.
  // The font's glyph box runs from the baseline up one em (ascent 1000, descent 0), so a baseline
  // on the box's bottom edge and a size equal to the box height make the text cover the line.
  const x = placement.origin.x + left * placement.scale;
  const y = placement.origin.y + placement.heightPt - (top + height) * placement.scale;
  const size = boxHeightPt;
  const naturalWidthPt = (count * GLYPH_ADVANCE * size) / 1000;
  const squeezePercent = (boxWidthPt / naturalWidthPt) * 100;

  page.pushOperators(
    pushGraphicsState(),
    beginText(),
    setFontAndSize(fontName, size),
    setTextRenderingMode(TextRenderingMode.Invisible),
    setCharacterSqueeze(squeezePercent),
    setTextMatrix(1, 0, 0, 1, x, y),
    showText(PDFHexString.of(hex)),
    endText(),
    popGraphicsState()
  );
  stats.linesDrawn++;
}

// Writes the page's OCR lines as invisible, selectable, searchable text over the page image.
export function drawOcrTextLayer(page: PDFPage, fontRef: PDFRef, ocr: PageOcr, placement: TextLayerPlacement): TextLayerStats {
  const fontName = PDFName.of(FONT_RESOURCE_NAME);
  page.node.setFontDictionary(fontName, fontRef);
  const stats: TextLayerStats = { linesDrawn: 0, skippedChars: 0 };
  for (const block of ocr.blocks) {
    for (const line of block.lines) drawLine(page, fontName, line, placement, stats);
  }
  return stats;
}
